export default interface Paciente {
    id : string,
    codigo: number,
    nombre : string,
    apellido : number,
    cedula : string,
    edad : string,
    fecha : string,
    sexo : string,
    direccion : string,
    sintomas : string,
    diagnostico : string,
    tratamiento : string,
    observaciones : string,
}